services:
  backend:
    image: hotel-backend
    build:
      context: backend
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017/hotel
      # Comment out the above line and uncomment the below lines if you want to use secrets from GitHub
      # - MONGO_CONNECTION_STRING=${MONGO_URI}
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./backend/src:/app/src

  frontend:
    image: hotel-frontend
    build:
      context: frontend
      dockerfile: dockerfile
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
