services:
  api:
    image: api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    # depends_on:
    #  - db
    env_file:
      - .env
    environment:
      - APP_NAME=api
    volumes:
      - ./src:/app/src

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
