services:
  api:
    image: hotel-api
    build:
      context: backend
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    env_file:
      - backend/.env
    environment:
      - APP_NAME=api
    volumes:
      - ./backend/src:/app/src

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
