@startuml Use Cases UML Diagram

left to right direction

skinparam Shadowing false
skinparam Monochrome true
skinparam PackageStyle rectangle

actor User
actor Hotel_Manager

package "User Management" {
  usecase "Create a User account" as UC1
}

package "Booking" {
  usecase "Make a booking" as UC2
  usecase "Check availability" as UC3
  usecase "Cancel a booking" as UC4
  usecase "View all bookings" as UC5
}

User --> UC1
User --> UC2
Hotel_Manager --> UC3
Hotel_Manager --> UC4
User --> UC5

@enduml
