name: 'Run tests on PR'

on: pull_request
# Use this when we have a backend folder
# on:
#   pull_request:
#     paths:
#       - 'backend/**'

jobs:
  check-run-tests:
    runs-on: ubuntu-latest
    # Use this when we have a backend folder
    # defaults:
    #   run:
    #     working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '20.3'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
        run: npm run test
